sudo: false

language: cpp

services:
  - docker

env:
  matrix:
    - QT="5.5_gcc"
    - QT="5.5_clang"
    - QT="5.6_gcc"
    - QT="5.6_clang"
    - QT="5.7_gcc"
    - QT="5.7_clang"

before_install:
  - ./docker/generateDockerfile.sh -t docker/Dockerfile.template -e qt=$QT >> Dockerfile

install:
  - docker build -t gorzechowski/gwatchd .

script:
  - docker run --rm gorzechowski/gwatchd bash --login /opt/gwatchd/scripts/check.sh
