sudo: false

services:
  - docker

env:
  matrix:
    - QT_VERSION="5.6_gcc"
    - QT_VERSION="5.6_clang"
    - QT_VERSION="5.7_gcc"
    - QT_VERSION="5.7_clang"

before_install:
  - ./docker/generateDockerfile.sh -t docker/Dockerfile.template -e qt=$QT_VERSION >> Dockerfile

install:
  - docker build -t gorzechowski/gwatchd .

script:
  - docker run --rm gorzechowski/gwatchd bash --login /opt/gwatchd/scripts/check.sh
